# Generated by Django 6.0.5 on 2026-05-30 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

operations = [
    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.RemoveField(
                model_name="product",
                name="desciption",
            ),
        ],
    ),

    migrations.AddField(
        model_name="product",
        name="description",
        field=models.TextField(default=""),
        preserve_default=False,
    ),

    migrations.AlterField(
        model_name="product",
        name="countInStock",
        field=models.IntegerField(default=0),
    ),

    migrations.AlterField(
        model_name="product",
        name="image",
        field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
    ),

    migrations.CreateModel(
        name="CartUser",
        fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("qty", models.IntegerField(default=1)),
            ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.product")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ],
    ),
]